name: Call a reusable workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  call-workflow-version-1:
    uses: ./.github/workflows/generate_image.yml
    environment: ecr
    secrets: inherit
    with:
      working_directory: ./version_1
      image_tag: ver1
  call-workflow-version-2:
    uses: ./.github/workflows/generate_image.yml
    environment: ecr
    secrets: inherit
    with:
      working_directory: ./version_2
      image_tag: ver2
