name: Call a reusable workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  call-workflow-version-1:
    uses: ./.github/workflows/generate_artifact.yml
    secrets: inherit
    with:
      WORKDIR: ./version_1
      IMAGE_TAG: ver1
      DOCKERFILE: Dockerfile
  call-workflow-version-2:
    uses: ./.github/workflows/generate_artifact.yml
    secrets: inherit
    with:
      WORKDIR: ./version_2
      IMAGE_TAG: ver2
      DOCKERFILE: Dockerfile
